//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kanzeed.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ADDRESSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_ADDRESSES()
        {
            this.DELIVERIES = new HashSet<DELIVERIES>();
        }
    
        public int address_id { get; set; }
        public int customer_id { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string street { get; set; }
        public int house { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<int> apartment { get; set; }
        public Nullable<int> porch { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERIES> DELIVERIES { get; set; }
    }
}
