//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kanzeed.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERIES
    {
        public int delivery_id { get; set; }
        public int order_id { get; set; }
        public int delivery_method_id { get; set; }
        public int address_id { get; set; }
        public Nullable<System.DateTime> estimated_date { get; set; }
        public decimal delivery_cost { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual CUSTOMER_ADDRESSES CUSTOMER_ADDRESSES { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual DELIVERY_METHODS DELIVERY_METHODS { get; set; }
        public virtual ORDERS ORDERS { get; set; }
    }
}
