//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kanzeed.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.DELIVERIES = new HashSet<DELIVERIES>();
            this.ORDER_ITEMS = new HashSet<ORDER_ITEMS>();
        }
    
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal total_amount { get; set; }
        public int status_id { get; set; }
        public int payment_method_id { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERIES> DELIVERIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public virtual ORDER_STATUSES ORDER_STATUSES { get; set; }
        public virtual PAYMENT_METHODS PAYMENT_METHODS { get; set; }
    }
}
