//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kanzeed.ApplicationData
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.ORDER_ITEMS = new HashSet<ORDER_ITEMS>();
        }
        public BitmapImage CurrentPhoto
        {
            get
            {
                try
                {
                    string relativePath = string.IsNullOrWhiteSpace(image)
                        ? Path.Combine("Images", "nofoto.png")
                        : image;

                    string fullPath = Path.Combine(
                        AppDomain.CurrentDomain.BaseDirectory,
                        relativePath
                    );

                    if (!File.Exists(fullPath))
                        return null;

                    var bmp = new BitmapImage();
                    bmp.BeginInit();
                    bmp.CacheOption = BitmapCacheOption.OnLoad;
                    bmp.UriSource = new Uri(fullPath, UriKind.Absolute);
                    bmp.EndInit();

                    return bmp;
                }
                catch
                {
                    return null;
                }
            }
        }
        public int product_id { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public int category_id { get; set; }
        public int supplier_id { get; set; }
        public int stock_quantity { get; set; }
        public string image { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public virtual SUPPLIERS SUPPLIERS { get; set; }
    }
}
